---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:12.2.2
  amd64: ghcr.io/hassio-addons/base/amd64:12.2.2
  armhf: ghcr.io/hassio-addons/base/armhf:12.2.2
  armv7: ghcr.io/hassio-addons/base/armv7:12.2.2
  i386: ghcr.io/hassio-addons/base/i386:12.2.2
labels:
  io.hass.type: addon
  io.hass.version: "1.0.0"
  org.opencontainers.image.description: "Print labels directly from Home Assistant using a Dymo LabelWriter 400"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.source: "https://github.com/MaxGramser/homeassistant_dymoLW400"
  org.opencontainers.image.title: "Dymo LabelWriter 400"
  org.opencontainers.image.vendor: "MaxGramser" 
