name: "Dymo Label Printer"
version: "1.0.0"
slug: "dymo_printer"
description: "Print labels on Dymo LabelWriter 450 via HTTP requests"
url: "https://github.com/yourusername/ha-dymo-printer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
usb: true
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web interface
map:
  - config:rw